# Generated by Django 5.1.4 on 2025-01-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('movies_orders', '0001_initial'),
        ('users', '0002_rename_birth_date_user_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='movies_purchased',
            field=models.ManyToManyField(related_name='user_buyers', through='movies_orders.MovieOrder', to='movies.movie'),
        ),
    ]
